# Generated by Django 4.0.4 on 2022-05-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_page_delete_songs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
